### ISSUE TITLE
Review existing codebase via the synthetic_demo notebook.

### ISSUE THREAD

**Issue by bringingjoy** [jakeval/MRMC#5]
Plan: start by walking through the synthetic_demo; when things are unclear, refer to checked-in code (and current commit #3). If code is unclear, bringingjoy@ will leave comment for improvement or create an issue.

Note: for time being, will ignore plot generation code

**Comment by jakeval** [comment]
Note: relevant files are
* data/adult_income/adult_data_adapter.py
* data/data_preprocessor.py
* demos/mrmc_synthetic_demo.ipynb
* recourse_methods/*
* core/recourse_iterator.py

**Comment by bringingjoy** [comment]
Done a while back and forgot to close the issue.
